test:
    path: /test/test
    defaults:  { _controller: Analyzer\Controller\ProductAnalyzerController::testRecord }
    methods: POST

product_add:
    path: /test/product/product-add
    defaults: { _controller: Products\Controller\ProductsController::productAdd }
    methods: POST

product_fafadel:
    path: /test/test2
    defaults: { _controller: Analyzer\Controller\ProductAnalyzerController::getStatistics}
    methods: POST
